/**
 * CelebrationToast — Sprint 31, the "you saved $X" delight moment.
 *
 * Why this exists
 * ---------------
 * The audit flagged Delightfulness at 8.3/10 with one specific gap:
 * "no celebratory moments after major actions". When the user
 * cancels a subscription that the engine knew about, the row just
 * fades out — there's no "nice, that's $14.99/mo / $179.88/yr you
 * just clawed back". This component is that moment.
 *
 * Pattern
 * -------
 * - ``useCelebrate()`` returns a ``celebrate(event)`` function and the
 *   list of currently-visible events.
 * - Panels call ``celebrate({ kind: "cancel_sub", monthlyCents: 1499,
 *   label: "Calm" })`` after a successful mutation.
 * - Each event auto-fades after 4.5s; multiple stack.
 * - A module-level ``sessionSavings`` counter tallies the running
 *   total this browser session so any panel (e.g., Money found's
 *   header) can render "you've saved $X today" if it wants.
 *
 * No external deps; this is a 60-line component + 30-line hook.
 */
import { useEffect, useRef, useState } from "react";
import { fmtCents } from "../api/client";

export interface CelebrationEvent {
  /** Unique id so React can key the rendered list. Generated by the hook. */
  id: number;
  /** What kind of action just succeeded — drives the headline copy. */
  kind: "cancel_sub" | "dismiss_sub" | "duplicate_resolved" | "custom";
  /** Optional recurring savings amount in cents per month. Always positive.
   *  Use for subscription cancels / duplicate-resolved cases where saving
   *  scales with time. The toast subline shows "$X/mo · $Y/yr saved". */
  monthlyCents?: number;
  /** Sprint 47 — optional one-time amount in cents (legal claim payouts,
   *  unclaimed-property cheques, card signup bonuses). Rendered as a
   *  "$X received" subline. Mutually exclusive with monthlyCents; if both
   *  are set, monthlyCents wins (preserves Sprint 31 behavior). */
  oneTimeCents?: number;
  /** Human-readable subject of the action (e.g. "Calm", "Peacock Premium"). */
  label?: string;
  /** Override the auto-generated headline. */
  headline?: string;
}

interface InternalEvent extends CelebrationEvent {
  /** Wall-clock ms the toast was fired. Used for the auto-hide timer. */
  firedAt: number;
}

// Module-level session counter. Resets on page reload. Exposed via
// ``getSessionSavings()`` so the Money found panel (or anyone else)
// can mirror it without subscribing to the hook.
let _sessionSavingsCents = 0;
const _sessionListeners = new Set<(total: number) => void>();

export function getSessionSavings(): number {
  return _sessionSavingsCents;
}

export function subscribeSessionSavings(
  fn: (total: number) => void,
): () => void {
  _sessionListeners.add(fn);
  return () => _sessionListeners.delete(fn);
}

function _emitSessionSavings(amountCents: number): void {
  _sessionSavingsCents += amountCents;
  for (const fn of _sessionListeners) fn(_sessionSavingsCents);
}

/* ------------------------------------------------------------------ */
/*  useCelebrate — emit + render a queue of celebration toasts.        */
/* ------------------------------------------------------------------ */

interface UseCelebrateState {
  events: InternalEvent[];
  celebrate: (e: Omit<CelebrationEvent, "id">) => void;
}

const _AUTO_HIDE_MS = 4500;
let _nextId = 1;

export function useCelebrate(): UseCelebrateState {
  const [events, setEvents] = useState<InternalEvent[]>([]);
  const timersRef = useRef<Map<number, number>>(new Map());

  // Clear any pending timers on unmount so we don't fire setState on
  // a dead component if the panel navigates away mid-toast.
  useEffect(() => {
    const timers = timersRef.current;
    return () => {
      for (const t of timers.values()) window.clearTimeout(t);
      timers.clear();
    };
  }, []);

  function celebrate(input: Omit<CelebrationEvent, "id">) {
    const id = _nextId++;
    const evt: InternalEvent = { ...input, id, firedAt: Date.now() };
    setEvents((prev) => [...prev, evt]);
    // Tally the session counter when it's a real-dollars event.
    if (
      typeof evt.monthlyCents === "number" &&
      evt.monthlyCents > 0 &&
      (evt.kind === "cancel_sub" || evt.kind === "duplicate_resolved")
    ) {
      _emitSessionSavings(evt.monthlyCents);
    }
    const handle = window.setTimeout(() => {
      setEvents((prev) => prev.filter((e) => e.id !== id));
      timersRef.current.delete(id);
    }, _AUTO_HIDE_MS);
    timersRef.current.set(id, handle);
  }

  return { events, celebrate };
}

/* ------------------------------------------------------------------ */
/*  CelebrationToastStack — render the queue.                          */
/* ------------------------------------------------------------------ */

interface ToastStackProps {
  events: InternalEvent[];
}

function _headlineFor(e: InternalEvent): string {
  if (e.headline) return e.headline;
  const labelTxt = e.label ? ` ${e.label}` : "";
  switch (e.kind) {
    case "cancel_sub":
      return `Nice — cancelled${labelTxt}.`;
    case "dismiss_sub":
      return `Dismissed${labelTxt}.`;
    case "duplicate_resolved":
      return `Duplicate resolved${labelTxt}.`;
    default:
      return "Done.";
  }
}

function _savingsLineFor(e: InternalEvent): string | null {
  // Recurring savings (subscription cancel etc.) take precedence — both
  // the line copy and the session-total semantics treat monthlyCents as
  // a per-month figure projected out to annual.
  if (e.monthlyCents && e.monthlyCents > 0) {
    const annualCents = e.monthlyCents * 12;
    return `${fmtCents(e.monthlyCents)}/mo · ${fmtCents(annualCents)}/yr saved`;
  }
  // Sprint 47 — one-time payout (legal claim, unclaimed property, card
  // signup bonus). Rendered as a flat "$X received" line; we don't
  // multiply by 12 because this isn't recurring income.
  if (e.oneTimeCents && e.oneTimeCents > 0) {
    return `${fmtCents(e.oneTimeCents)} received`;
  }
  return null;
}

export function CelebrationToastStack({ events }: ToastStackProps) {
  if (events.length === 0) return null;
  return (
    <div
      className="fixed bottom-6 left-1/2 -translate-x-1/2 z-50 flex flex-col items-center gap-2 pointer-events-none"
      role="status"
      aria-live="polite"
    >
      {events.map((e) => {
        const savings = _savingsLineFor(e);
        return (
          <div
            key={e.id}
            className="bg-inflow text-white rounded-md shadow-lg px-4 py-2.5 flex items-center gap-3 animate-in slide-in-from-bottom-2 fade-in duration-200"
          >
            <span className="text-base leading-none" aria-hidden="true">
              ✓
            </span>
            <div className="flex flex-col">
              <span className="text-sm font-semibold">{_headlineFor(e)}</span>
              {savings && (
                <span className="text-[11px] opacity-90 tabular-nums">
                  {savings}
                </span>
              )}
            </div>
          </div>
        );
      })}
    </div>
  );
}
